#!/bin/bash
# Date : (2011-11-28 22-00)
# Last revision : (2011-12-04 10-59)
# Wine version used : 1.3.27-rawinput2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite <petchema@concept-micro.com>
# Script licence : GPL v.2
# Program licence : Freeware
# Depend : unzip

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

abort () {
    POL_SetupWindow_message "$(eval_gettext 'An error occurred, the installation is aborted.')" "$TITLE"
    POL_SetupWindow_Close
    exit 1
}

check_install_archive () {
    POL_SetupWindow_wait "$(eval_gettext 'Checking install archive...')" "$TITLE"

    EXPECTED_NAME='OUTCASTP_V3.zip'
    EXPECTED_SIZE=102462783
    EXPECTED_MD5="d1c6783339150684c659d5fb56f130dc"

    # Temporarily prevent word splitting
    OLDIFS="$IFS"
    IFS=''
    NAME="$(basename $ARCHIVE)"
    SIZE="$(stat -c%s $ARCHIVE)"
    MD5="$(POL_MD5_file $ARCHIVE)"
    IFS="$OLDIFS"

    POL_SetupWindow_detect_exit

    if [ $SIZE -ne $EXPECTED_SIZE -o "$MD5" != "$EXPECTED_MD5" ]; then
        POL_SetupWindow_message "$(eval_gettext 'Install archive mismatch.\nEither your install archive is corrupted, or is not the expected version.\nThis script cannot guarantee that installation will work correctly. Please report success or failure to PlayOnLinux forums.')\n$(eval_gettext 'Name:') $NAME ($(eval_gettext 'expected') $EXPECTED_NAME)\n$(eval_gettext 'Size:') $SIZE ($(eval_gettext 'expected') $EXPECTED_SIZE)\n$(eval_gettext 'MD5:') $MD5\n     ($(eval_gettext 'expected') $EXPECTED_MD5)" "$TITLE"
        POL_SetupWindow_question "$(eval_gettext 'Continue?')" "$TITLE"
        [ "$APP_ANSWER" != "TRUE" ] && abort
    fi
}

# Must match outcast-gog script values
PREFIX="Outcast_gog"
SHORTCUT_NAME="Outcast"

TITLE="$(eval_gettext 'Zenger s Outcast HI-RES patch v3')"
SHORTCUT_NAME="$(eval_gettext 'Zenger Hi-Res patch v3')"

POL_SetupWindow_Init
POL_Debug_Init
# URL shortener? :p
POL_SetupWindow_presentation "$TITLE" "Zenger" "http://www.gog.com/en/forum/outcast/...\nexperimental_outcast_hi_res_patch...\n_up_to_1280x768_cyana_lighthouse_problem_fixed/" "Pierre Etchemaite" "$PREFIX"

check_one "unzip" "unzip"
POL_SetupWindow_missing

if [ "$(POL_Wine_PrefixExists $PREFIX)" != "True" ]; then
    POL_SetupWindow_message "$(eval_gettext 'Oops, you must install Outcast (GoG release) first!')" "$TITLE"
    abort
fi

POL_Wine_SelectPrefix "$PREFIX"
POL_LoadVar_PROGRAMFILES

POL_SetupWindow_message "$(eval_gettext 'You can download the archive file from:')\nhttp://www.megaupload.com/?d=H6CIR27L" "$TITLE"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE"
ARCHIVE="$APP_ANSWER"

check_install_archive

POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

unzip -n "$ARCHIVE" -d "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Outcast/" || abort

POL_SetupWindow_message "$(eval_gettext 'The patch can now be activated and configured from\nPlayOnLinux s setup wizard for Outcast.\nAnd dont forget to leave a message to Zenger on GoG forums!')" "$TITLE"

POL_SetupWindow_Close

cat <<EOF > $REPERTOIRE/configurations/configurators/"$SHORTCUT_NAME".zenger-hires

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Outcast/" || return
[ -e APPLYMEGAPATCH.exe ] || return

POL_SetupWindow_question "$(eval_gettext 'Run \$TITLE?')" "\$TITLE"
if [ "\$APP_ANSWER" = "TRUE" ]; then

    POL_SetupWindow_wait "\$TITLE" "\$TITLE"

    POL_Wine APPLYMEGAPATCH.exe

    SCREEN_WIDTH=\$(grep '^ScreenWidth=' OUTCAST.ini |cut -d= -f2)
    SCREEN_HEIGHT=\$(grep '^ScreenHeight=' OUTCAST.ini |cut -d= -f2)
    Set_Desktop "On" "\$SCREEN_WIDTH" "\$SCREEN_HEIGHT"

    POL_SetupWindow_message "$(eval_gettext 'Check that the resolution has been changed\n(eventually set to \"HI-RES\") in the loader.')" "\$TITLE"

fi
EOF
