#!/bin/bash
# Date : (2011-11-27 19-47)
# Last revision : (2011-11-28 01-44)
# Wine version used : 1.3.27-rawinput2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite <petchema@concept-micro.com>
# Script licence : GPL v.2
# Program licence : Retail
# Depend : none

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

abort () {
    POL_SetupWindow_message_image "$LNG_ABORTED" "$TITLE" "$PLAYONLINUX/themes/tango/warning.png"
    POL_SetupWindow_Close
    exit 1
}

check_install_archive () {
    POL_SetupWindow_wait_next_signal "$LNG_CHECK_ARCHIVE" "$TITLE"

    EXPECTED_SIZE=1409323648
    EXPECTED_MD5="a8bf2336a580527f0eb99f8b90009c33"

    SIZE="$(stat -c%s $ARCHIVE)"
    MD5="$(md5sum $ARCHIVE|cut -c1-32)"

    POL_SetupWindow_detect_exit

    if [ $SIZE -ne $EXPECTED_SIZE -o "$MD5" != "$EXPECTED_MD5" ]; then
        POL_SetupWindow_message_image "$LNG_ARCHIVE_MISMATCH\nSize: $SIZE (expected $EXPECTED_SIZE)\nMD5: $MD5\n     (expected $EXPECTED_MD5)" "$TITLE" "$PLAYONLINUX/themes/tango/warning.png"
        POL_SetupWindow_question "$LNG_CONTINUE" "$TITLE"
        [ "$APP_ANSWER" != "TRUE" ] && abort
    fi
}


PREFIX="Outcast_gog"
WORKING_WINE_VERSION="1.3.27-rawinput2"

case "$POL_LANG" in
    fr)
        TITLE="Outcast (version GoG)"
        SHORTCUT_NAME="Outcast"
        SHORTCUT_DOC="Manuel de l'utilisateur Outcast"
        LNG_ABORTED="Une erreur est survenue, l'installation est interrompue."
        LNG_CHECK_ARCHIVE="Test de l'archive d'installation..."
        LNG_ARCHIVE_MISMATCH="L'archive ne correspond pas.\nOu bien elle est corrompue, ou ce n'est pas la version attendue.\nCe script ne peut pas garantir que l'installation se passera bien, pensez à communiquer le résultat de l'installation sur le forum de PlayOnLinux."
	LNG_CONTINUE="Continuer ?"
        LNG_ARCHIVE_LOCATION="Indiquez l'emplacement de l'archive d'installation"
        LNG_SELECT_FILE="Sélectionnez le fichier"
        LNG_INSTALLING="Installation de $SHORTCUT_NAME..."
        ;;
    *)
        TITLE="Outcast (GoG release)"
        SHORTCUT_NAME="Outcast"
        SHORTCUT_DOC="Outcast user manual"
        LNG_ABORTED="An error occurred, the installation is aborted."
        LNG_CHECK_ARCHIVE="Checking install archive..."
        LNG_ARCHIVE_MISMATCH="Install archive mismatch.\nEither your install archive is corrupted, or is not the expected version.\nThis script cannot guarantee that installation will work correctly. Please report success or failure to PlayOnLinux forums."
        LNG_CONTINUE="Continue?"
        LNG_ARCHIVE_LOCATION="Please select the location of the install file"
        LNG_SELECT_FILE="Select file"
        LNG_INSTALLING="Installing $SHORTCUT_NAME..."
        ;;
esac

POL_SetupWindow_Init
POL_SetupWindow_presentation "$TITLE" "Appeal S.A. / Atari" "http://www.gog.com/en/gamecard/outcast" "Pierre Etchemaite" "$PREFIX"
 
 
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate
POL_LoadVar_PROGRAMFILES

cd $HOME
POL_SetupWindow_browse "$LNG_ARCHIVE_LOCATION" "$LNG_SELECT_FILE"
ARCHIVE="$APP_ANSWER"

check_install_archive

POL_Wine_InstallVersion "$WORKING_WINE_VERSION"
export WINEVERSION="$WORKING_WINE_VERSION"


POL_SetupWindow_wait_next_signal "$LNG_INSTALLING" "$TITLE"

# Associate .PDF with native app 
# http://wiki.winehq.org/FAQ#head-91bf3f0a8ccbfab8dee96f82fae2f1a489e0d243
# Do it before installing the game, so you have the possibility to open
# PDFs with Win32 reader if you choose to install it
cat <<'EOF' > $REPERTOIRE/tmp/pdfnativereader.reg
[HKEY_CLASSES_ROOT\.pdf]
@="PDFfile"
"Content Type"="application/pdf"
[HKEY_CLASSES_ROOT\PDFfile\Shell\Open\command]
@="winebrowser \"%1\""
EOF
POL_Wine regedit $REPERTOIRE/tmp/pdfnativereader.reg


POL_Wine "$ARCHIVE" || abort

# GoG work!
Set_OS winxp

# Main game will crash if desktop size is not constrained
Set_Desktop "On" "640" "480"

# Only works perfectly with rawinput; Otherwise makes loader menu funky
# (grab the menu around to put wanted entry at the center of screen,
# release then click!), but the rest of the game is more enjoyable
#Set_DXGrab "On"


# Set_GrabFullScreen anyone?
cat <<'EOF' > $REPERTOIRE/tmp/grabfullscreen.reg
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\X11 Driver]
"GrabFullscreen"="Y"
EOF
POL_Wine regedit $REPERTOIRE/tmp/grabfullscreen.reg

POL_SetupWindow_detect_exit

# Doesn't hurt ;)
POL_Wine_reboot 


# Warning, /windows/command/ also contains a start.exe, so
# POL_SetupWindow_auto_shortcut or POL_Shortcut can fail
POL_SetupWindow_make_shortcut "$PREFIX" "$PROGRAMFILES/GOG.com/Outcast/" "start.exe" "" "$SHORTCUT_NAME"
cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Outcast/Outcast.ICO" "$REPERTOIRE/icones/32/$SHORTCUT_NAME"
Set_WineVersion_Assign "$WORKING_WINE_VERSION" "$SHORTCUT_NAME"

POL_SetupWindow_make_shortcut "$PREFIX" "/windows/command" "start.exe" "" "$SHORTCUT_DOC" "" "'C:/$PROGRAMFILES/GOG.com/Outcast/manual.pdf'"


POL_SetupWindow_Close

cat <<EOF > $REPERTOIRE/configurations/configurators/Outcast
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="$REPERTOIRE/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

case "\$POL_LANG" in
    fr)
        TITLE="Outcast (version Gog)"
        LNG_CHOOSE_LANGUAGE="Choisissez le langage des voix et des sous-titres"
        ;;
    *)
        TITLE="Outcast (GoG release)"
        LNG_CHOOSE_LANGUAGE="Choose language for voices and subtitles"
        ;;
esac

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Outcast/" || exit 1

CURRENT_LANG=English
[ -f pol_configuration ] && source pol_configuration

POL_SetupWindow_Init

# Other language directories are incomplete (?)
POL_SetupWindow_menu_list "\$LNG_CHOOSE_LANGUAGE" "\$TITLE" "English~French~German" "~" "\$CURRENT_LANG"
CURRENT_LANG="\$APP_ANSWER"
case "\$CURRENT_LANG" in
    English)
        ln -sf Data/Voices/ENGLISH/FIX.PAK fix.pak
        ln -sf Data/Voices/ENGLISH/TEXT.PAK text.pak
        ln -sf Data/Voices/ENGLISH/VOICES1.PAK voices1+.pak
        ln -sf Data/Voices/ENGLISH/VOICES2.PAK voices2+.pak
        ln -sf Data/Voices/ENGLISH/VOICES3.PAK voices3+.pak
        ln -sf Data/Voices/ENGLISH/VOICES4.PAK voices4+.pak
        ln -sf Data/Voices/ENGLISH/VOICES5.PAK voices5+.pak
        ln -sf Data/Voices/ENGLISH/VOICES6.PAK voices6+.pak
        ln -sf Data/Voices/ENGLISH/VOICESGE.PAK voicesgen+.pak
        ;;
    French)
        ln -sf Data/Voices/French/FIX.PAK fix.pak
        ln -sf Data/Voices/French/TEXT.PAK text.pak
        ln -sf Data/Voices/French/VOICES1.PAK voices1+.pak
        ln -sf Data/Voices/French/VOICES2.PAK voices2+.pak
        ln -sf Data/Voices/French/VOICES3.PAK voices3+.pak
        ln -sf Data/Voices/French/VOICES4.PAK voices4+.pak
        ln -sf Data/Voices/French/VOICES5.PAK voices5+.pak
        ln -sf Data/Voices/French/VOICES6.PAK voices6+.pak
        ln -sf Data/Voices/French/VOICESGE.PAK voicesgen+.pak
        ;;
    German)
        ln -sf Data/Voices/German/FIX.PAK fix.pak
        ln -sf Data/Voices/German/TEXT.PAK text.pak
        ln -sf Data/Voices/German/VOICES1.PAK voices1+.pak
        ln -sf Data/Voices/German/VOICES2.PAK voices2+.pak
        ln -sf Data/Voices/German/VOICES3.PAK voices3+.pak
        ln -sf Data/Voices/German/VOICES4.PAK voices4+.pak
        ln -sf Data/Voices/German/VOICES5.PAK voices5+.pak
        ln -sf Data/Voices/German/VOICES6.PAK voices6+.pak
        ln -sf Data/Voices/German/VOICESGE.PAK voicesgen+.pak
        ;;
esac

# Allow for extensions
shopt -s nullglob
for conf in \$REPERTOIRE/configurations/configurators/Outcast.*; do
    source "\$conf"
done

echo "CURRENT_LANG=\"\$CURRENT_LANG\"" > pol_configuration

POL_SetupWindow_Close
exit

EOF

exit
