#!/bin/bash
# Date : (2011-11-27 19-47)
# Last revision : (2011-11-28 01-44)
# Wine version used : 1.3.27-rawinput2
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite <petchema@concept-micro.com>
# Script licence : GPL v.2
# Program licence : Retail
# Depend : none

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

abort () {
    POL_SetupWindow_message_image "$LNG_ABORTED" "$TITLE" "$PLAYONLINUX/themes/tango/warning.png"
    POL_SetupWindow_Close
    exit 1
}

check_install_archive () {
    POL_SetupWindow_wait_next_signal "$LNG_CHECK_ARCHIVE" "$TITLE"

    EXPECTED_SIZE=1409323648
    EXPECTED_MD5="a8bf2336a580527f0eb99f8b90009c33"

    SIZE="$(stat -c%s $ARCHIVE)"
    MD5="$(md5sum $ARCHIVE|cut -c1-32)"

    POL_SetupWindow_detect_exit

    if [ $SIZE -ne $EXPECTED_SIZE -o "$MD5" != "$EXPECTED_MD5" ]; then
        POL_SetupWindow_message_image "$LNG_ARCHIVE_MISMATCH\nSize: $SIZE (expected $EXPECTED_SIZE)\nMD5: $MD5\n     (expected $EXPECTED_MD5)" "$TITLE" "$PLAYONLINUX/themes/tango/warning.png"
        POL_SetupWindow_question "$LNG_CONTINUE" "$TITLE"
        [ "$APP_ANSWER" != "TRUE" ] && abort
    fi
}


PREFIX="Outcast_gog"
WORKING_WINE_VERSION="1.3.27-rawinput2"

case "$POL_LANG" in
    fr)
        TITLE="Outcast (version GoG)"
        SHORTCUT_NAME="Outcast"
        SHORTCUT_DOC="Manuel de l'utilisateur Outcast"
        LNG_ABORTED="Une erreur est survenue, l'installation est interrompue."
        LNG_CHECK_ARCHIVE="Test de l'archive d'installation..."
        LNG_ARCHIVE_MISMATCH="L'archive ne correspond pas.\nOu bien elle est corrompue, ou ce n'est pas la version attendue.\nCe script ne peut pas garantir que l'installation se passera bien, pensez à communiquer le résultat de l'installation sur le forum de PlayOnLinux."
	LNG_CONTINUE="Continuer ?"
        LNG_ARCHIVE_LOCATION="Indiquez l'emplacement de l'archive d'installation"
        LNG_SELECT_FILE="Sélectionnez le fichier"
        LNG_INSTALLING="Installation de $SHORTCUT_NAME..."
        ;;
    *)
        TITLE="Outcast (GoG release)"
        SHORTCUT_NAME="Outcast"
        SHORTCUT_DOC="Outcast user manual"
        LNG_ABORTED="An error occurred, the installation is aborted."
        LNG_CHECK_ARCHIVE="Checking install archive..."
        LNG_ARCHIVE_MISMATCH="Install archive mismatch.\nEither your install archive is corrupted, or is not the expected version.\nThis script cannot guarantee that installation will work correctly. Please report success or failure to PlayOnLinux forums."
        LNG_CONTINUE="Continue?"
        LNG_ARCHIVE_LOCATION="Please select the location of the install file"
        LNG_SELECT_FILE="Select file"
        LNG_INSTALLING="Installing $SHORTCUT_NAME..."
        ;;
esac

POL_SetupWindow_Init
POL_SetupWindow_presentation "$TITLE" "Appeal S.A. / Atari" "http://www.gog.com/en/gamecard/outcast" "Pierre Etchemaite" "$PREFIX"
 
 
POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate
POL_LoadVar_PROGRAMFILES

cd $HOME
POL_SetupWindow_browse "$LNG_ARCHIVE_LOCATION" "$LNG_SELECT_FILE"
ARCHIVE="$APP_ANSWER"

check_install_archive

POL_Wine_InstallVersion "$WORKING_WINE_VERSION"
export WINEVERSION="$WORKING_WINE_VERSION"


POL_SetupWindow_wait_next_signal "$LNG_INSTALLING" "$TITLE"

# Associate .PDF with native app 
# http://wiki.winehq.org/FAQ#head-91bf3f0a8ccbfab8dee96f82fae2f1a489e0d243
# Do it before installing the game, so you have the possibility to open
# PDFs with Win32 reader if you choose to install it
cat <<'EOF' > $REPERTOIRE/tmp/pdfnativereader.reg
[HKEY_CLASSES_ROOT\.pdf]
@="PDFfile"
"Content Type"="application/pdf"
[HKEY_CLASSES_ROOT\PDFfile\Shell\Open\command]
@="winebrowser \"%1\""
EOF
POL_Wine regedit $REPERTOIRE/tmp/pdfnativereader.reg


POL_Wine "$ARCHIVE" || abort

# GoG work!
Set_OS winxp

# Main game will crash if desktop size is not constrained
Set_Desktop "On" "640" "480"

# Only works perfectly with rawinput; Otherwise makes loader menu funky
# (grab the menu around to put wanted entry at the center of screen,
# release then click!), but the rest of the game is more enjoyable
#Set_DXGrab "On"


# Set_GrabFullScreen anyone?
cat <<'EOF' > $REPERTOIRE/tmp/grabfullscreen.reg
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\X11 Driver]
"GrabFullscreen"="Y"
EOF
POL_Wine regedit $REPERTOIRE/tmp/grabfullscreen.reg

POL_SetupWindow_detect_exit

# Doesn't hurt ;)
POL_Wine_reboot 


# Warning, /windows/command/ also contains a start.exe, so
# POL_SetupWindow_auto_shortcut or POL_Shortcut can fail
POL_SetupWindow_make_shortcut "$PREFIX" "$PROGRAMFILES/GOG.com/Outcast/" "start.exe" "" "$SHORTCUT_NAME"
cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Outcast/Outcast.ICO" "$REPERTOIRE/icones/32/$SHORTCUT_NAME"
Set_WineVersion_Assign "$WORKING_WINE_VERSION" "$SHORTCUT_NAME"

POL_SetupWindow_make_shortcut "$PREFIX" "/windows/command" "start.exe" "" "$SHORTCUT_DOC" "" "'C:/$PROGRAMFILES/GOG.com/Outcast/manual.pdf'"


POL_SetupWindow_Close

cat <<EOF > $REPERTOIRE/configurations/configurators/Outcast
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="$REPERTOIRE/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

case "\$POL_LANG" in
    fr)
        TITLE="Outcast (version Gog)"
        LNG_CHOOSE_LANGUAGE="Choisissez la langue"
        ;;
    *)
        TITLE="Outcast (GoG release)"
        LNG_CHOOSE_LANGUAGE="Choose language"
        ;;
esac

cd "\$WINEPREFIX/drive_c/\$PROGRAMFILES/GOG.com/Outcast/" || exit 1

CURRENT_LANG=English
[ -f pol_configuration ] && source pol_configuration

POL_SetupWindow_Init

# Other language directories are incomplete (?)
POL_SetupWindow_menu_list "\$LNG_CHOOSE_LANGUAGE" "\$TITLE" "English~French~German~Brasilian (text only)~Dutch (text only)~Italian (text only)~Spanish (text only)" "~" "\$CURRENT_LANG"
if [ "\$CURRENT_LANG" != "\$APP_ANSWER" ]; then
    CURRENT_LANG="\$APP_ANSWER"
    case "\$CURRENT_LANG" in
	English)
	    ln -sf Data/Voices/ENGLISH/FIX.PAK fix.pak
	    ln -sf Data/Voices/ENGLISH/TEXT.PAK text.pak
	    ln -sf Data/Voices/ENGLISH/VOICES1.PAK voices1+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES2.PAK voices2+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES3.PAK voices3+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES4.PAK voices4+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES5.PAK voices5+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES6.PAK voices6+.pak
	    ln -sf Data/Voices/ENGLISH/VOICESGE.PAK voicesgen+.pak
	    ;;
	French)
	    ln -sf Data/Voices/French/FIX.PAK fix.pak
	    ln -sf Data/Voices/French/TEXT.PAK text.pak
	    ln -sf Data/Voices/French/VOICES1.PAK voices1+.pak
	    ln -sf Data/Voices/French/VOICES2.PAK voices2+.pak
	    ln -sf Data/Voices/French/VOICES3.PAK voices3+.pak
	    ln -sf Data/Voices/French/VOICES4.PAK voices4+.pak
	    ln -sf Data/Voices/French/VOICES5.PAK voices5+.pak
	    ln -sf Data/Voices/French/VOICES6.PAK voices6+.pak
	    ln -sf Data/Voices/French/VOICESGE.PAK voicesgen+.pak
	    ;;
	German)
	    ln -sf Data/Voices/German/FIX.PAK fix.pak
	    ln -sf Data/Voices/German/TEXT.PAK text.pak
	    ln -sf Data/Voices/German/VOICES1.PAK voices1+.pak
	    ln -sf Data/Voices/German/VOICES2.PAK voices2+.pak
	    ln -sf Data/Voices/German/VOICES3.PAK voices3+.pak
	    ln -sf Data/Voices/German/VOICES4.PAK voices4+.pak
	    ln -sf Data/Voices/German/VOICES5.PAK voices5+.pak
	    ln -sf Data/Voices/German/VOICES6.PAK voices6+.pak
	    ln -sf Data/Voices/German/VOICESGE.PAK voicesgen+.pak
	    ;;
        "Brasilian (text only)")
	    ln -sf Data/Voices/Brasilian/FIX.PAK fix.pak
	    ln -sf Data/Voices/Brasilian/TEXT.PAK text.pak
	    ln -sf Data/Voices/ENGLISH/VOICES1.PAK voices1+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES2.PAK voices2+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES3.PAK voices3+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES4.PAK voices4+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES5.PAK voices5+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES6.PAK voices6+.pak
	    ln -sf Data/Voices/ENGLISH/VOICESGE.PAK voicesgen+.pak
            ;;
        "Dutch (text only)")
	    ln -sf Data/Voices/Dutch/FIX.PAK fix.pak
	    ln -sf Data/Voices/Dutch/TEXT.PAK text.pak
	    ln -sf Data/Voices/ENGLISH/VOICES1.PAK voices1+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES2.PAK voices2+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES3.PAK voices3+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES4.PAK voices4+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES5.PAK voices5+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES6.PAK voices6+.pak
	    ln -sf Data/Voices/ENGLISH/VOICESGE.PAK voicesgen+.pak
            ;;
        "Italian (text only)")
	    ln -sf Data/Voices/Italian/FIX.PAK fix.pak
	    ln -sf Data/Voices/Italian/TEXT.PAK text.pak
	    ln -sf Data/Voices/ENGLISH/VOICES1.PAK voices1+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES2.PAK voices2+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES3.PAK voices3+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES4.PAK voices4+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES5.PAK voices5+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES6.PAK voices6+.pak
	    ln -sf Data/Voices/ENGLISH/VOICESGE.PAK voicesgen+.pak
            ;;
        "Spanish (text only)")
	    ln -sf Data/Voices/Spanish/FIX.PAK fix.pak
	    ln -sf Data/Voices/Spanish/TEXT.PAK text.pak
	    ln -sf Data/Voices/ENGLISH/VOICES1.PAK voices1+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES2.PAK voices2+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES3.PAK voices3+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES4.PAK voices4+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES5.PAK voices5+.pak
	    ln -sf Data/Voices/ENGLISH/VOICES6.PAK voices6+.pak
	    ln -sf Data/Voices/ENGLISH/VOICESGE.PAK voicesgen+.pak
            ;;
    esac
fi

POL_SetupWindow_menu "\$LNG_CHOOSE_KEYBOARD_LAYOUT" "\$TITLE" "Unchanged~Arrow keys (default)~WASD (Qwerty)~ZQSD (Azerty)" "~" "Unchanged"
case "\$APP_ANSWER" in
    Unchanged)
        ;;
    "Arrow keys (default)")
        # LF -> CRLF mantra
        cat <<'MAPEOF' | sed 's/$'"/`echo \\\r`/" > Control.ini
[Trigger]
Slow=KEY_RALT     
Rudder_LeftRight=~MOUSE_AXIS_0 JOY_AXIS_3
RudderRight=JOYBUT7
RudderMotion=KEY_LALT     
RudderLeft=JOYBUT6
BackForward=JOY_AXIS_1
LeftRight=JOY_AXIS_0
CameraFar=||KEY_NUMPAD1 JOYBUT258 KEY_END
CameraNear=||KEY_NUMPAD7 JOYBUT256 KEY_HOME
Forward=|KEY_NUMPAD8 KEY_UP     
Backward=|KEY_NUMPAD2 KEY_DOWN     
Left=|KEY_NUMPAD4 KEY_LEFT     
Right=|KEY_NUMPAD6 KEY_RIGHT     
Fire=||MOUSE_BUTTON_0 JOYBUT0 KEY_LCONTROL
Target=||MOUSE_BUTTON_1 JOYBUT1 KEY_LSHIFT
MapZoomout=KEY_SUBTRACT     
MapZoomin=KEY_ADD     
MapToggleSize=KEY_MULTIPLY     
Map=KEY_TAB     
Inventory=|KEY_I JOYBUT6     
WeaponPrevious=KEY_NUMPAD3     
WeaponNext=KEY_NUMPAD9     
Weapon6=KEY_6     
Weapon5=KEY_5     
Weapon4=KEY_4     
Weapon3=KEY_3     
Weapon2=KEY_2     
Weapon1=KEY_1     
XRay=KEY_X     
PitchUp=|JOYBUT259 KEY_PAGEUP     
PitchDown=|JOYBUT257 KEY_PAGEDOWN     
Pitch=MOUSE_AXIS_1
Notepad=KEY_N     
BackPack=KEY_B     
Lexicon=KEY_L     
LockTarget=KEY_K     
ClearHands=KEY_0     
Abort=|KEY_ESCAPE JOYBUT1
Escape=KEY_ESCAPE
Crawl=|JOYBUT4 KEY_SPACE     
Jump=JOYBUT5
FirstPerson=|JOYBUT7 KEY_RCONTROL     
PitchAbsolute=JOY_AXIS_2
VolumeUp=KEY_R     
VolumeDown=KEY_E     
MouseUp=KEY_V     
MouseDown=KEY_C     
BalanceUp=KEY_F     
BalanceDown=KEY_D     
CameraRight=
CameraLeft=
disablejoystick=0

[Sensitivity]
MouseSensitivity=0.500000
InvertedMouse=-1.000000
swapmousebuttons=0

[Sound_Quality_Control]
3D_sound=1
EAX_support=1
MAPEOF
	;;
    "WASD (Qwerty)")
        cat <<'MAPEOF' | sed 's/$'"/`echo \\\r`/" > Control.ini
[Trigger]
Slow=KEY_RALT
Rudder_LeftRight=~MOUSE_AXIS_0 JOY_AXIS_3
RudderRight=JOYBUT7
RudderMotion=KEY_LALT
RudderLeft=JOYBUT6
BackForward=JOY_AXIS_1
LeftRight=JOY_AXIS_0
CameraFar=||KEY_NUMPAD1 JOYBUT258 KEY_END
CameraNear=||KEY_NUMPAD7 JOYBUT256 KEY_HOME
Forward=||KEY_W KEY_NUMPAD8 KEY_UP
Backward=||KEY_S KEY_NUMPAD2 KEY_DOWN
Left=||KEY_A KEY_NUMPAD4 KEY_LEFT
Right=||KEY_D KEY_NUMPAD6 KEY_RIGHT
Fire=|MOUSE_BUTTON_0 KEY_LCONTROL
Target=||MOUSE_BUTTON_1 JOYBUT1 KEY_LSHIFT
MapZoomout=KEY_SUBTRACT
MapZoomin=KEY_ADD
MapToggleSize=KEY_MULTIPLY
Map=KEY_TAB
Inventory=|KEY_R JOYBUT6
WeaponPrevious=|KEY_NUMPAD3 KEY_Z
WeaponNext=|KEY_NUMPAD9 KEY_Q
Weapon6=KEY_6
Weapon5=KEY_5
Weapon4=KEY_4
Weapon3=KEY_3
Weapon2=KEY_2
Weapon1=KEY_1
XRay=KEY_X
PitchUp=|JOYBUT259 KEY_PAGEUP
PitchDown=|JOYBUT257 KEY_PAGEDOWN
Pitch=MOUSE_AXIS_1
Notepad=KEY_T
BackPack=KEY_B
Lexicon=KEY_L
LockTarget=KEY_E
ClearHands=|KEY_0 KEY_V
Abort=|KEY_ESCAPE JOYBUT1
Escape=KEY_ESCAPE
Crawl=||JOYBUT4 KEY_C KEY_SPACE
Jump=JOYBUT5
FirstPerson=||JOYBUT7 KEY_RCONTROL KEY_F
PitchAbsolute=JOY_AXIS_2
VolumeUp=KEY_U
VolumeDown=KEY_Y
MouseUp=KEY_I
MouseDown=KEY_K
BalanceUp=KEY_J
BalanceDown=KEY_H
CameraRight=
CameraLeft=
disablejoystick=0

[Sensitivity]
MouseSensitivity=0.500000
InvertedMouse=-1.000000
swapmousebuttons=0

[Sound_Quality_Control]
3D_sound=1
EAX_support=1
MAPEOF
	;;
    "ZQSD (Azerty)")
        cat <<'MAPEOF' | sed 's/$'"/`echo \\\r`/" > Control.ini
[Trigger]
Slow=KEY_RALT
Rudder_LeftRight=~MOUSE_AXIS_0 JOY_AXIS_3
RudderRight=JOYBUT7
RudderMotion=KEY_LALT
RudderLeft=JOYBUT6
BackForward=JOY_AXIS_1
LeftRight=JOY_AXIS_0
CameraFar=||KEY_NUMPAD1 JOYBUT258 KEY_END
CameraNear=||KEY_NUMPAD7 JOYBUT256 KEY_HOME
Forward=||KEY_Z KEY_NUMPAD8 KEY_UP
Backward=||KEY_S KEY_NUMPAD2 KEY_DOWN
Left=||KEY_Q KEY_NUMPAD4 KEY_LEFT
Right=||KEY_D KEY_NUMPAD6 KEY_RIGHT
Fire=|MOUSE_BUTTON_0 KEY_LCONTROL
Target=||MOUSE_BUTTON_1 JOYBUT1 KEY_LSHIFT
MapZoomout=KEY_SUBTRACT
MapZoomin=KEY_ADD
MapToggleSize=KEY_MULTIPLY
Map=KEY_TAB
Inventory=|KEY_R JOYBUT6
WeaponPrevious=|KEY_NUMPAD3 KEY_W
WeaponNext=|KEY_NUMPAD9 KEY_A
Weapon6=KEY_6
Weapon5=KEY_5
Weapon4=KEY_4
Weapon3=KEY_3
Weapon2=KEY_2
Weapon1=KEY_1
XRay=KEY_X
PitchUp=|JOYBUT259 KEY_PAGEUP
PitchDown=|JOYBUT257 KEY_PAGEDOWN
Pitch=MOUSE_AXIS_1
Notepad=KEY_T
BackPack=KEY_B
Lexicon=KEY_L
LockTarget=KEY_E
ClearHands=|KEY_0 KEY_V
Abort=|KEY_ESCAPE JOYBUT1
Escape=KEY_ESCAPE
Crawl=||JOYBUT4 KEY_C KEY_SPACE
Jump=JOYBUT5
FirstPerson=||JOYBUT7 KEY_RCONTROL KEY_F
PitchAbsolute=JOY_AXIS_2
VolumeUp=KEY_U
VolumeDown=KEY_Y
MouseUp=KEY_I
MouseDown=KEY_K
BalanceUp=KEY_J
BalanceDown=KEY_H
CameraRight=
CameraLeft=
disablejoystick=0

[Sensitivity]
MouseSensitivity=0.500000
InvertedMouse=-1.000000
swapmousebuttons=0

[Sound_Quality_Control]
3D_sound=1
EAX_support=1
MAPEOF
	;;
esac


# Allow for extensions
shopt -s nullglob
for conf in \$REPERTOIRE/configurations/configurators/Outcast.*; do
    source "\$conf"
done

echo "CURRENT_LANG=\"\$CURRENT_LANG\"" > pol_configuration

POL_SetupWindow_Close
exit

EOF

exit
