#!/bin/bash
# Date : (2012-12-01 22-38)
# Last revision : (2011-12-03 17-30)
# Wine version used : 1.3.23
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite <petchema@concept-micro.com>
# Script licence : GPL v.2
# Program licence : Retail
# Depend : dosbox

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

check_install_archive () {
    POL_SetupWindow_wait "$(eval_gettext 'Checking install archive...')" "$TITLE"

    EXPECTED_NAME='setup_starflight_1_2.exe'
    EXPECTED_SIZE=44526203
    EXPECTED_MD5="4b3e884d1bbe066470338456991dc73e"

    # Temporarily prevent word splitting
    OLDIFS="$IFS"
    IFS=''
    NAME="$(basename $ARCHIVE)"
    SIZE="$(stat -c%s $ARCHIVE)"
    MD5="$(POL_MD5_file $ARCHIVE)"
    IFS="$OLDIFS"

    if [ $SIZE -ne $EXPECTED_SIZE -o "$MD5" != "$EXPECTED_MD5" ]; then
        POL_Debug_Error "$(eval_gettext 'Install archive mismatch.\nEither your install archive is corrupted, or is not the expected version.\nThis script cannot guarantee that installation will work correctly. Please report success or failure to PlayOnLinux forums.')\n$(eval_gettext 'Name:') $NAME ($(eval_gettext 'expected') $EXPECTED_NAME)\n$(eval_gettext 'Size:') $SIZE ($(eval_gettext 'expected') $EXPECTED_SIZE)\n$(eval_gettext 'MD5:') $MD5\n     ($(eval_gettext 'expected') $EXPECTED_MD5)"
        POL_SetupWindow_question "$(eval_gettext 'Continue?')" "$TITLE"
        [ "$APP_ANSWER" != "TRUE" ] && POL_Debug_Fatal "$(eval_gettext 'Not the expected archive')"
    fi
}


PREFIX="Starflight_1_2_gog"
WORKING_WINE_VERSION="1.3.23"
# GoG tools (graphic mode setup, code wheel work _almost_ ok with 1.3.23
# but are broken (controls don't react to clicks) with 1.3.33

TITLE="$(eval_gettext 'Starflight 1 and 2 (GoG release)')"
SHORTCUT1_NAME="Starflight 1"
SHORTCUT1_CODEWHEEL="$SHORTCUT1_NAME - $(eval_gettext 'Code wheel')"
SHORTCUT1_DOC="$SHORTCUT1_NAME - $(eval_gettext 'User manual')"
SHORTCUT1_MAP="$SHORTCUT1_NAME - $(eval_gettext 'Stellar map')"
SHORTCUT2_NAME="Starflight 2"
SHORTCUT2_DOC="$SHORTCUT2_NAME - $(eval_gettext 'User manual')"
SHORTCUT2_MAP="$SHORTCUT2_NAME - $(eval_gettext 'Stellar map')"

POL_SetupWindow_Init
POL_Debug_Init
POL_SetupWindow_presentation "$TITLE" "Binary Systems / Electronic Arts" "http://www.gog.com/en/gamecard/starflight_1_2" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE"
ARCHIVE="$APP_ANSWER"

check_install_archive

POL_SetupWindow_question "$(eval_gettext 'This game uses the DOSBox emulator, that also exists natively for Linux.\nUse native version when present? (Recommended)')" "$TITLE"
NATIVEDOSBOX=''
[ "$APP_ANSWER" = "TRUE" ] && NATIVEDOSBOX=1

# SF1 original interface for game backups involved DOS prompt, restoring this (almost: start in game however)
SF1DROPINCONSOLE=1


POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Associate .PDF with native app
# http://wiki.winehq.org/FAQ#head-91bf3f0a8ccbfab8dee96f82fae2f1a489e0d243
# Do it before installing the game, so you have the possibility to open
# PDFs with Win32 reader if you choose to install it
cat <<'EOF' > $REPERTOIRE/tmp/pdfnativereader.reg
[HKEY_CLASSES_ROOT\.pdf]
@="PDFfile"
"Content Type"="application/pdf"
[HKEY_CLASSES_ROOT\PDFfile\Shell\Open\command]
@="winebrowser \"%1\""
EOF
POL_Wine regedit $REPERTOIRE/tmp/pdfnativereader.reg
rm $REPERTOIRE/tmp/pdfnativereader.reg

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

# GoG work!
Set_OS winxp

# Doesn't hurt ;)
POL_Wine_reboot

# Sadly, it seems GoG installer unpacks both games even if you only ask for 1
# So test below is uneffective and all shortcuts are always created
if [ -d "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1" ]; then
    # Better default settings in my opinion
    sed -i.orig -e 's/^output=.*/output=OpenGL/; s/^cycles=.*/cycles=auto/; s/^fullscreen=.*/fullscreen=false/; s/^scaler=.*/scaler=hq2x/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/dosboxSF1.conf"

    # GoG default
    DOSBOX_PARAMS='-conf dosboxSF1.conf -noconsole -c "exit"'
    if [ -n "$SF1DROPINCONSOLE" ]; then
        DOSBOX_PARAMS='-conf dosboxSF1.conf -noconsole'
        cat <<-EOFINI > $REPERTOIRE/tmp/sf1dropinconsole.reg
	[HKEY_LOCAL_MACHINE\Software\GOG.com\GOGSTARFLIGHT1]
	"DOSBOXPARAM"="$DOSBOX_PARAMS"
	"LAUNCHCOMMAND"="\"C:\\Program Files\\GOG.com\\Starflight 1 and 2\\DOSBOX\\dosbox.exe\" $DOSBOX_PARAMS"
	EOFINI
        POL_Wine regedit $REPERTOIRE/tmp/sf1dropinconsole.reg
        rm $REPERTOIRE/tmp/sf1dropinconsole.reg
        sed -i -e 's/^exit.*/type HDNOTESA.TXT/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/dosboxSF1.conf"
    fi

    POL_SetupWindow_make_shortcut "$PREFIX" "$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/" "C:/$PROGRAMFILES/GOG.com/Starflight 1 and 2/DOSBOX/DOSBox.exe" "" "$SHORTCUT1_NAME" "" "$DOSBOX_PARAMS"
    cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/gfw_high.ico" "$REPERTOIRE/icones/32/$SHORTCUT1_NAME"
    if [ -n "$NATIVEDOSBOX" ]; then
        # Thanks to exec, will only start W32 dosbox if native dosbox fails to start
        POL_Shortcut_InsertBeforeWine "$SHORTCUT1_NAME" "exec dosbox $DOSBOX_PARAMS"
    fi

    POL_Shortcut "Starflight_codes_by_gog.exe" "$SHORTCUT1_CODEWHEEL"

    POL_Shortcut "start.exe" "$SHORTCUT1_DOC" "" "'C:/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/manual.pdf'"

    POL_Shortcut "start.exe" "$SHORTCUT1_MAP" "" "'C:/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 1/map.pdf'"
fi

if [ -d "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2" ]; then
    # Better default settings in my opinion
    sed -i.orig -e 's/^output=.*/output=OpenGL/; s/^fullscreen=.*/fullscreen=false/; s/^scaler=.*/scaler=hq2x/' "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/dosboxSF2.conf"

    POL_SetupWindow_make_shortcut "$PREFIX" "$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/" "C:/$PROGRAMFILES/GOG.com/Starflight 1 and 2/DOSBOX/DOSBox.exe" "" "$SHORTCUT2_NAME" "" "-conf dosboxSF2.conf -noconsole -c \"exit\""
    cp -n "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/gfw_high.ico" "$REPERTOIRE/icones/32/$SHORTCUT2_NAME"
    if [ -n "$NATIVEDOSBOX" ]; then
        # Thanks to exec, will only start W32 dosbox if native dosbox fails to start
        POL_Shortcut_InsertBeforeWine "$SHORTCUT2_NAME" "exec dosbox -conf dosboxSF2.conf"
    fi

    POL_Shortcut "start.exe" "$SHORTCUT2_DOC" "" "'C:/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/manual.pdf'"

    POL_Shortcut "start.exe" "$SHORTCUT2_MAP" "" "'C:/$PROGRAMFILES/GOG.com/Starflight 1 and 2/Starflight 2/map.pdf'"
fi

POL_SetupWindow_Close

cat <<EOF > $REPERTOIRE/configurations/configurators/"$SHORTCUT1_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="$REPERTOIRE/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/" || exit

if [ -n "$NATIVEDOSBOX" ]; then
    # Make sure that if user presses "start game", it will launch the right dosbox
    DOSBOX="`which dosbox`"
    if [ -n "\$DOSBOX" ]; then
	cat <<-EOFINI > $REPERTOIRE/tmp/sf1nativedosbox.reg
	REGEDIT4

	[HKEY_LOCAL_MACHINE\Software\GOG.com\GOGSTARFLIGHT1]
	"LAUNCHCOMMAND"="\$DOSBOX -conf dosboxSF1.conf"
	EOFINI
        POL_Wine regedit $REPERTOIRE/tmp/sf1nativedosbox.reg
        rm $REPERTOIRE/tmp/sf1nativedosbox.reg
    fi
fi

POL_Wine "Graphic mode setup.exe" "GOGSTARFLIGHT1"
exit
EOF

cat <<EOF > $REPERTOIRE/configurations/configurators/"$SHORTCUT2_NAME"
#!/bin/bash
[ -z "\$PLAYONLINUX" ] && exit 0
source "\$PLAYONLINUX/lib/sources"
export WINEPREFIX="$REPERTOIRE/wineprefix/$PREFIX"
export WINEDEBUG=""

POL_LoadVar_PROGRAMFILES

cd "$WINEPREFIX/drive_c/$PROGRAMFILES/GOG.com/Starflight 1 and 2/" || exit

if [ -n "$NATIVEDOSBOX" ]; then
    # Make sure that if user presses "start game", it will launch the right dosbox
    DOSBOX="`which dosbox`"
    if [ -n "\$DOSBOX" ]; then
	cat <<-EOFINI > $REPERTOIRE/tmp/sf2nativedosbox.reg
	REGEDIT4

	[HKEY_LOCAL_MACHINE\Software\GOG.com\GOGSTARFLIGHT2]
	"LAUNCHCOMMAND"="\$DOSBOX -conf dosboxSF2.conf"
	EOFINI
        POL_Wine regedit $REPERTOIRE/tmp/sf2nativedosbox.reg
        rm $REPERTOIRE/tmp/sf2nativedosbox.reg
    fi
fi

POL_Wine "Graphic mode setup.exe" "GOGSTARFLIGHT2"
exit
EOF

exit
