#!/bin/bash
# Date : (2012-12-14 02-03)
# Last revision : (2011-12-14 02-03)
# Wine version used : 1.3.34
# Distribution used to test : Debian Sid (Unstable)
# Author : Pierre Etchemaite petchema@concept-micro.com
# Script licence : GPL v.2
# Program licence : Retail
# Depend :

[ -z "$PLAYONLINUX" ] && exit 0
source "$PLAYONLINUX/lib/sources"

check_install_archive () {
    FILE="$1"
    EXPECTED_NAME="$2"
    EXPECTED_SIZE="$3"
    EXPECTED_MD5="$4"

    POL_SetupWindow_wait "$(eval_gettext 'Checking install archive...')" "$TITLE"
    # Temporarily prevent word splitting
    OLDIFS="$IFS"
    IFS=''
    NAME="$(basename $FILE)"
    SIZE="$(stat -c%s $FILE)"
    MD5="$(POL_MD5_file $FILE)"
    IFS="$OLDIFS"

    if [ $SIZE -ne $EXPECTED_SIZE -o "$MD5" != "$EXPECTED_MD5" ]; then
        POL_Debug_Error "$(eval_gettext 'Install archive mismatch.\nEither your install archive is corrupted, or is not the expected version.\nThis script cannot guarantee that installation will work correctly. Please report success or failure to PlayOnLinux forums.')\n$(eval_gettext 'Name:') $NAME ($(eval_gettext 'expected') $EXPECTED_NAME)\n$(eval_gettext 'Size:') $SIZE ($(eval_gettext 'expected') $EXPECTED_SIZE)\n$(eval_gettext 'MD5:') $MD5\n     ($(eval_gettext 'expected') $EXPECTED_MD5)"
        POL_SetupWindow_question "$(eval_gettext 'Continue?')" "$TITLE"
        [ "$APP_ANSWER" != "TRUE" ] && POL_Debug_Fatal "$(eval_gettext 'Not the expected archive')"
    fi
}


PREFIX="EmpireEarth_gog"
WORKING_WINE_VERSION="1.3.34"

TITLE="$(eval_gettext 'Empire Earth: Gold Edition (GoG release)')"
SHORTCUT_NAME1="Empire Earth"
SHORTCUT_DOC1="$SHORTCUT_NAME1 - $(eval_gettext 'Manual')"
SHORTCUT_DOC_TECHTREE1="$SHORTCUT_NAME1 - $(eval_gettext 'Technology tree')"
SHORTCUT_DOC_EDITOR1="$SHORTCUT_NAME1 - $(eval_gettext 'Scenario editor manual')"
SHORTCUT_NAME2="Empire Earth: The Art of Conquest"
SHORTCUT_DOC2="$SHORTCUT_NAME2 - $(eval_gettext 'Manual')"
SHORTCUT_DOC_TECHTREE2="$SHORTCUT_NAME2 - $(eval_gettext 'Technology tree')"
SHORTCUT_README2="$SHORTCUT_NAME2 - $(eval_gettext 'Readme')"

POL_SetupWindow_Init
POL_Debug_Init

POL_SetupWindow_presentation "$TITLE" "Stainless Steel Studios / Rebellion" "http://www.gog.com/en/gamecard/empire_earth_gold_edition" "Pierre Etchemaite" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate "$WORKING_WINE_VERSION"

cd $HOME
POL_SetupWindow_browse "$(eval_gettext 'Please select the setup file to run.')" "$TITLE"
ARCHIVE="$APP_ANSWER"

check_install_archive "$ARCHIVE" setup_empire_earth_gold.exe 564162686 1d5c5587ab26488b3a38f1ba288ce89a


POL_SetupWindow_wait "$(eval_gettext 'Please wait while $TITLE is installed.')" "$TITLE"

# Associate .PDF with native app
# http://wiki.winehq.org/FAQ#head-91bf3f0a8ccbfab8dee96f82fae2f1a489e0d243
# Do it before installing the game, so you have the possibility to open
# PDFs with Win32 reader if you choose to install it
cat <<'_EOF_' > $REPERTOIRE/tmp/pdfnativereader.reg
[HKEY_CLASSES_ROOT\.pdf]
@="PDFfile"
"Content Type"="application/pdf"
[HKEY_CLASSES_ROOT\PDFfile\Shell\Open\command]
@="winebrowser \"%1\""
_EOF_
POL_Wine regedit $REPERTOIRE/tmp/pdfnativereader.reg

POL_Wine_InstallFonts

POL_Wine start /unix "$ARCHIVE" || POL_Debug_Fatal "$(eval_gettext 'Error while installing archive')"

POL_Wine_WaitExit "$TITLE"

POL_Call POL_install_vcrun6

cat <<_EOFINI_ > "$REPERTOIRE/tmp/disable_directmusic.reg"
REGEDIT4

[HKEY_CURRENT_USER\Software\SSSI\Empire Earth]
"Music Enabled"=dword:00000000
_EOFINI_
POL_Wine regedit "$REPERTOIRE/tmp/disable_directmusic.reg"
rm "$REPERTOIRE/tmp/disable_directmusic.reg"

# GoG work!?
Set_OS win2k

POL_SetupWindow_VMS "4"

POL_Wine_X11Drv "DXGrab" "Y"
POL_Wine_X11Drv "GrabFullScreen" "Y"

## PlayOnMac Section
[ -n "$PLAYONMAC" ] && Set_SoundDriver "alsa"
[ -n "$PLAYONMAC" ] || Set_Managed "Off"
## End Section

# Doesn't hurt ;)
POL_Wine_reboot

POL_Shortcut "Empire Earth.exe" "$SHORTCUT_NAME1"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME1" "POL_Wine_AutoSetVersionEnv\nwineserver -k\nnice -19 wineserver"
POL_Shortcut "start.exe" "$SHORTCUT_DOC1" "" "'C:/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth/Manual.pdf'"
POL_Shortcut "start.exe" "$SHORTCUT_DOC_TECHTREE1" "" "'C:/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth/technology_tree.pdf'"
POL_Shortcut "start.exe" "$SHORTCUT_DOC_EDITOR1" "" "'C:/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth/scenario_editor_manual.pdf'"

POL_Shortcut "EE-AOC.exe" "$SHORTCUT_NAME2"
POL_Shortcut_InsertBeforeWine "$SHORTCUT_NAME2" "POL_Wine_AutoSetVersionEnv\nwineserver -k\nnice -19 wineserver"
POL_Shortcut "start.exe" "$SHORTCUT_README2" "" "'C:/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth - The Art of Conquest/readme.txt'"
POL_Shortcut "start.exe" "$SHORTCUT_DOC2" "" "'C:/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth - The Art of Conquest/manual_aoc.pdf'"
POL_Shortcut "start.exe" "$SHORTCUT_DOC_TECHTREE2" "" "'C:/$PROGRAMFILES/GOG.com/Empire Earth Gold Edition/Empire Earth - The Art of Conquest/technology_tree_aoc.pdf'"

POL_SetupWindow_Close
exit
